samples: demo_samples.csv
name: demo
reference: ""
min_bin_size: 250
min_days_span: 7
max_days_span: 21
seq_per_bin: 
- 250
- 650
- 850
days_per_bin:
- 7
- 14
- 21
freq_cutoff: 2
reported_cases:
- demo_reported_cases.csv
- ","
- date
- newCases
- '%Y-%m-%d'
masking: "1-10,29000-30000"
smoothing_bandwidth_phi: 14
smoothing_bandwidth_mi: 7
from_date: ""
to_date: ""
